### ISSUE TITLE
Recoil not changing bullet direction

### ISSUE THREAD

**Issue by liquiddevelopmentnet** [andrewlalis/ace-of-shades-2#8]
https://cdn.liqbn.com/aa6f51c894f7e312ceb08c0e20ce2d90/7552d7b9a3d62b0237b815981242e0f1.mp4

**Comment by andrewlalis** [comment]
Thank you, I shall address this shortly

**Comment by andrewlalis** [comment]
Should be fixed by: 492b9f66aa140ec8ac9b985d89891649db4b9b6c
